services:

#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile-frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - ./Backend:/app
      - data:/data
    ports:
      - "8000:8000"


# Daten persistieren für container machen
volumes:
  data:

#  frontend:
#    build:
#      context: ./Project/frontend            # erstelle später ./Project/frontend mit React
#      dockerfile: Dockerfile-backend-backend
#    container_name: lazycook_frontend
#    restart: "no"
#    volumes:
#      - ./Project/frontend:/app
#      - /app/node_modules
#    environment:
#      - CHOKIDAR_USEPOLLING=true             # nützlich für Live‑Reload auf Windows
#    ports:
#      - "3000:3000"